# Book settings
# https://jupyterbook.org/customize/config.html
title: NGS Data Analysis Training
author: Christine Tranchant-Dubreuil and François Sabot
copyright: "2020"
logo: img/Manipulation-of-NGS-Data-for-Genomic-and-Population-Genetics-Analyses-300x300.jpeg
#only_build_toc_files: true

launch_buttons:
  notebook_interface : "classic" 
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository:
  url          : https://github.com/tranchant/TS
  path_to_book : ""  # A path to your book's folder, relative to the repository root.
  branch       : master  # Which branch of the repository should be used when creating links

sphinx:
  extra_extensions:
    - sphinx_thebe
    
html:
  use_repository_button: true
