launch_buttons:
  notebook_interface : "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository:
  url          : https://tranchant.github.io/TS/
  path_to_book : ""  # A path to your book's folder, relative to the repository root.
  branch       : master  # Which branch of the repository should be used when creating links

sphinx:
  extra_extensions:
    - sphinx_thebe